CREATE TABLE T2 (
	XXNUMBER NUMBER,
	COL_A VARCHAR(3),
	col_B VARCHAR(1),
	LAST_UPDATE_DATE DATE,
	CONSTRAINT T2_PK PRIMARY KEY(XXNUMBER)
);

--ALTER TABLE T2 ADD UNIQUE(COL_A, COL_B, LAST_UPDATE_DATE);
ALTER TABLE T2 ADD UNIQUE(COL_A);
ALTER TABLE T2 ADD UNIQUE(COL_B);
ALTER TABLE T2 ADD UNIQUE(LAST_UPDATE_DATE);

INSERT INTO T2 VALUES (1,'ABC','1',SYSDATE);
INSERT INTO T2 VALUES (1,'BCD','2',SYSDATE+1);
INSERT INTO T2 VALUES (2,'ABC','1',SYSDATE);
INSERT INTO T2 VALUES (3,'BCD','2',SYSDATE+1);


SET SERVEROUTPUT ON
DECLARE
  lv_name VARCHAR2(30);
BEGIN
  DELETE FROM T2;
  COMMIT;
  lv_name := '1行目';
  INSERT INTO T2 VALUES (1,'ABC','1',SYSDATE);
  lv_name := '2行目';
  INSERT INTO T2 VALUES (2,'ABC','1',SYSDATE);
  lv_name := '3行目';
  INSERT INTO T2 VALUES (3,'BCD','2',SYSDATE);
  lv_name := '4行目';
  INSERT INTO T2 VALUES (1,'BCD','2',SYSDATE);
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(lv_name || ' >>> ' ||SQLERRM);
END;
/